-- Amsi Spaces — Cloudflare D1 schema
-- Init with: wrangler d1 execute amsi_spaces --file=./schema.sql
-- Note: property listings are NOT stored here — they're synced from Palmera
-- into KV (see src/lib/palmera.ts, src/pages/api/palmera-sync.ts). D1 only
-- holds Amsi's own operational data: leads, click logs, webhook events.

-- Leads captured from the shared enquiry footer. When project_source/
-- project_id are set and the visitor consented, this is also registered
-- with Palmera as a real lead (Track B) — palmera_lead_id/palmera_status
-- track that; palmera_status is then kept current by incoming webhooks
-- (see src/pages/api/palmera-webhook.ts), not polled.
CREATE TABLE IF NOT EXISTS leads (
  id TEXT PRIMARY KEY,                 -- uuid, generated by the Worker — also used as the
                                        -- Palmera Idempotency-Key, so a retry never double-creates
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  source_page TEXT NOT NULL,           -- e.g. '/properties', '/blog/some-post'
  interest TEXT,                       -- chip selected: buy/invest/finance/tools/courses/e-guides
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  contact_preference TEXT,             -- email/phone/whatsapp
  message TEXT,
  project_reference TEXT,              -- property title, for display/email only
  project_source TEXT,                 -- Palmera project.source (studio/wp/snap), if project-specific
  project_id TEXT,                     -- Palmera project.id, if project-specific
  market TEXT,                         -- market slug, if known
  consent_contact INTEGER NOT NULL DEFAULT 0,   -- required checkbox
  consent_marketing INTEGER NOT NULL DEFAULT 0, -- optional checkbox
  consent_text_version TEXT NOT NULL,  -- which version of consent copy was shown
  status TEXT NOT NULL DEFAULT 'new',  -- new | registered-with-partner | contacted | closed
  palmera_lead_id TEXT,                -- Palmera's own lead id, once POST /leads succeeds
  palmera_status TEXT,                 -- one of Palmera's 16 lead statuses; kept current by webhooks
  registered_with_partner_at TEXT,     -- set when POST /leads to Palmera succeeds
  ip_hash TEXT,                        -- hashed, not raw, for basic abuse tracking
  user_agent TEXT
);

CREATE INDEX IF NOT EXISTS idx_leads_status ON leads(status);
CREATE INDEX IF NOT EXISTS idx_leads_created_at ON leads(created_at);
CREATE INDEX IF NOT EXISTS idx_leads_palmera_lead_id ON leads(palmera_lead_id);

-- Palmera webhook events — deduped on Palmera's own event id, per the
-- brief's receiver rule ("delivery is at least once by design").
CREATE TABLE IF NOT EXISTS palmera_webhook_events (
  id TEXT PRIMARY KEY,                 -- Palmera's event id (Palmera-Webhook-Id)
  received_at TEXT NOT NULL DEFAULT (datetime('now')),
  type TEXT NOT NULL,                  -- lead.created | lead.status_changed | commission.accrued | ...
  occurred_at TEXT NOT NULL,           -- when the thing actually happened, per Palmera
  raw_payload TEXT NOT NULL            -- full event JSON, for replay/debugging
);

CREATE INDEX IF NOT EXISTS idx_palmera_webhook_events_type ON palmera_webhook_events(type);

-- Click logs for /go/:partner redirects (Tools/Courses/partner e-guide
-- affiliate links). Palmera "View project" clicks go straight to Palmera's
-- shareUrl and are NOT routed through /go/, so they are not logged here.
CREATE TABLE IF NOT EXISTS click_logs (
  id TEXT PRIMARY KEY,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  partner_id TEXT NOT NULL,            -- matches Partner.id in src/data/partners.ts
  destination_url TEXT NOT NULL,
  source_page TEXT,
  ip_hash TEXT,
  user_agent TEXT
);

CREATE INDEX IF NOT EXISTS idx_click_logs_partner ON click_logs(partner_id);
CREATE INDEX IF NOT EXISTS idx_click_logs_created_at ON click_logs(created_at);

-- Partner registry (mirrors src/data/partners.ts so it can also be queried
-- from Worker code without redeploying, once partners are managed at runtime
-- rather than in source).
CREATE TABLE IF NOT EXISTS partners (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,              -- property | financing | tools | courses | e-guide
  markets TEXT NOT NULL,               -- JSON array of market slugs
  referral_mechanism TEXT NOT NULL,    -- api | manual | link
  label TEXT NOT NULL,                 -- referral-partner | sponsored
  referral_code TEXT,
  notes TEXT
);

-- E-guides (Amsi's own, sold via Gumroad, plus partner e-books that link out).
CREATE TABLE IF NOT EXISTS eguides (
  id TEXT PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  owner TEXT NOT NULL,                 -- amsi | partner
  type TEXT NOT NULL,                  -- free | paid
  price REAL,
  currency TEXT,
  topic TEXT,
  market TEXT,
  gumroad_product_id TEXT,             -- Amsi's own guides
  external_url TEXT,                   -- partner guides
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Gumroad Ping webhook events (sales/downloads), logged before forwarding
-- to n8n, so nothing is lost if the n8n forward fails.
CREATE TABLE IF NOT EXISTS gumroad_events (
  id TEXT PRIMARY KEY,
  received_at TEXT NOT NULL DEFAULT (datetime('now')),
  product_id TEXT,
  sale_id TEXT,
  email TEXT,
  price REAL,
  raw_payload TEXT NOT NULL,           -- full JSON, for replay/debugging
  forwarded_to_n8n INTEGER NOT NULL DEFAULT 0
);
